### ISSUE TITLE
Hash table needs improved documentation

### ISSUE THREAD

**Issue by Zer0-One** [Zer0-One/praetor#2]
02:38 <+iphy> Does [add] replace the old entry when one exists?
02:39 <+iphy> Does it do so by allocating, or does it modify the existing bucket?
02:39 <+iphy> I.e. in oom situations, can I still replace existing values?
02:39 <+iphy> What comparator is used?
02:43 <+iphy> What happens if load threshold is negative or 0 or above 1?
02:49 <+iphy> The hash function is not specific to add, so it should be specified in the hash table docs, not in the add docs

**Comment by Zer0-One** [comment]
@iphydf What do you think now?

**Comment by iphydf** [comment]
Another unanswered question: does the hashtable own the key's memory when you add it?

**Comment by Zer0-One** [comment]
@iphydf I think I answered this here: https://github.com/Zer0-One/praetor/blob/master/include/hashtable.h#L78-L79

Is that not sufficient?

**Comment by iphydf** [comment]
Ok, yes, that's sufficient. I suggest making everything `const` that can be. The API as it is suggests that the key will be written to by the add function.
