### ISSUE TITLE
irc_msg_send() for messages longer than MSG_SIZE_MAX

### ISSUE THREAD

**Issue by Zer0-One** [Zer0-One/praetor#8]
When `irc_msg_send()` is called with a message length greater than `MSG_SIZE_MAX`, praetor should optionally split the message into as many as needed to send the entire message.

Or, we can defer this to the caller. Not sure yet.

**Comment by GrayHatter** [comment]
Add a bool split or reject, so the caller doesn't have to implement word splitting. Or can get an error code, and split it's own way. Assuming this fxn will be exposed to the modules

**Comment by Zer0-One** [comment]
https://tools.ietf.org/html/rfc2812#section-2.3

>There is no provision for continuation of message lines.

`irc_msg_send()` needs to be re-written to be aware of the IRC message type, or message splitting needs to be implemented at a higher level.
